apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-web2
  template:
    metadata:
      labels:
        app: static-web2
    spec:
      containers:
      - name: nginx
        image: cuong111103hd/static-web2-nginx:latest
        ports:
        - containerPort: 80
