apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-web1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: static-web1
  template:
    metadata:
      labels:
        app: static-web1
    spec:
      containers:
      - name: nginx
        image: cuong111103hd/static-web-nginx:latest 
        ports:
        - containerPort: 80
